version: "3.7"

services:

  proxy:
    image: dockerflow/docker-flow-proxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - proxy
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm

  swarm-listener:
    image: dockerflow/docker-flow-swarm-listener
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]

  jenkins:
    image: shazchaudhry/docker-jenkins:latest
    user: root
    environment:
      - JENKINS_OPTS='--prefix=/jenkins'
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
    secrets: # See how secrets are used in this jenkins image at: https://github.com/shazChaudhry/docker-jenkins/blob/master/config/security.groovy
      - jenkins-user
      - jenkins-pass
    deploy:
      labels:
        - com.df.port=8080
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/jenkins

  jenkins_slave:
    image: vfarcic/jenkins-swarm-agent
    environment:
      - USER_NAME_SECRET=/run/secrets/${JENKINS_USER_SECRET:-jenkins-user}
      - PASSWORD_SECRET=/run/secrets/${JENKINS_PASS_SECRET:-jenkins-pass}
      # See slave options at: https://wiki.jenkins.io/display/JENKINS/Swarm+Plugin
      - COMMAND_OPTIONS=-master http://jenkins:8080/jenkins/ -description slave -mode exclusive -name slave -labels slave -executors 2
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_slave_workspace:/workspace
    secrets:
      - jenkins-user
      - source: jenkins-pass
        mode: 0400
    deploy:
      mode: global

secrets:
  jenkins-pass:
    external: true
  jenkins-user:
    external: true

volumes:
  jenkins_home:
    # See 'REX-Ray Docker volume plug-ins' documentaion; volume available across entire docker swarm cluster
    # https://rexray.readthedocs.io/en/v0.9.0/user-guide/docker-plugins/#elastic-block-service
    # driver: rexray/ebs
    # driver_opts:
    #   size: 5
  jenkins_slave_workspace:

networks:
  proxy:
